### ISSUE TITLE
Is project still open for development? 

### ISSUE THREAD

**Issue by edosssa** [alashow/datmusic-android#11]
Hey man! Love your work. I just wanted to know if this project is still open for active development. For starters, I feel the android app could use a few modifications. A particular comment on the play store suggested that the app incorporate some of the features of a full fledged media player and I agree.

**Comment by alashow** [comment]
Hey, thanks!

I didn't start datmusic app to make it a full fledhed music service, but simple music downloader with a preview.

I don't have much time to add features like audiplayer with a queue, playlists and etc. Currently, users can download mp3's and add use any local files audiplayer on Android (there a lot of them) to play them.

That being said, I'm to PR's for a better audio preview (ex. a background player for playing search results), UI updates (while keeping it minimal), bug fixes etc.

**Comment by king-kay** [comment]
I completely understand.

Still, since it's just going to be just a downloading service, how about a musicBrainz (or some other service) integration to fix the missing song metadata? Because I for one, cannot listen to music with missing metadata (ID3 tags). Plus it also helps to keep things tidy in apps like ITunes or Groove music. I'm guessing most people (purly subjective) feel the same way. 

P.S: I'm pretty sure this isn't a suitable place for such a feature suggestion, it should be in the Api reposiitory.

**Comment by alashow** [comment]
> Is project still open for development? 

update: Yes. I've started developing the new version today to learn new android stuff. Can't promise the player yet, but a better app with better search capabilities is coming!
